# Generated by Django 5.2.15 on 2026-06-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('icon', models.CharField(default='fas fa-folder', max_length=100, verbose_name='أيقونة')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البرنامج')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم البرنامج (إنجليزي)')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط')),
                ('product_type', models.CharField(choices=[('desktop', 'برنامج سطح المكتب'), ('web', 'تطبيق ويب'), ('mobile', 'تطبيق جوال')], default='desktop', max_length=20, verbose_name='نوع البرنامج')),
                ('short_description', models.TextField(max_length=300, verbose_name='وصف مختصر')),
                ('short_description_en', models.TextField(blank=True, max_length=300, verbose_name='وصف مختصر (إنجليزي)')),
                ('full_description', models.TextField(verbose_name='الوصف الكامل')),
                ('full_description_en', models.TextField(blank=True, verbose_name='الوصف الكامل (إنجليزي)')),
                ('features', models.TextField(help_text='اكتب كل ميزة في سطر منفصل', verbose_name='المميزات (كل ميزة في سطر)')),
                ('features_en', models.TextField(blank=True, verbose_name='المميزات (إنجليزي)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الرئيسية')),
                ('demo_url', models.URLField(blank=True, verbose_name='رابط النسخة التجريبية')),
                ('download_url', models.URLField(blank=True, verbose_name='رابط التحميل')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('price_label', models.CharField(blank=True, help_text='مثال: مجاني / تواصل للسعر', max_length=100, verbose_name='وصف السعر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'برنامج',
                'verbose_name_plural': 'البرامج',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='products.product', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'ordering': ['order'],
            },
        ),
    ]
